COMMON_SCHEMA_FIELD_NAMES = set(
    [
        "titre",
        "description",
        "mots_cles",
        "nom_orga",
        "siret_orga",
        "id_alt_orga",
        "service",
        "si",
        "contact_service",
        "contact_personne",
        "date_pub",
        "date_maj",
        "freq_maj",
        "couv_geo",
        "url",
        "format",
        "licence"
    ]
)
